/**
 * Vantage Seeker — System Model
 *
 * This file is the single source of truth for the domain types, provenance
 * labels, and operational modes used across the entire application.
 *
 * Rule: every number that reaches the UI must either be wrapped in
 * LabeledValue or live inside a result object with a `provenance` field.
 *
 * NOTE: We use const object maps instead of TypeScript enums because the
 * project enables `erasableSyntaxOnly`.
 */

/** Where a value came from. This is the honesty layer of the system. */
export const Provenance = {
  /** Derived from an external, verifiable source (e.g. Yahoo Finance closes). */
  real: 'real',
  /** Generated by a parametric model or simulation (e.g. GBM). */
  synthetic: 'synthetic',
  /** Hardcoded or purely cosmetic; not computed from data. */
  cosmetic: 'cosmetic',
  /** User-supplied configuration or preference. */
  config: 'config',
  /** Pure presentation/helper value with no analytical meaning. */
  presentation: 'presentation',
} as const
export type Provenance = (typeof Provenance)[keyof typeof Provenance]

/** A value plus its provenance and a human-readable source note. */
export interface LabeledValue<T> {
  value: T
  provenance: Provenance
  source: string
  note?: string
}

/** Operational mode of the application. Determines what "live" means. */
export const OperationalMode = {
  /** Browsing the catalog, formulas, glossary. No simulation running. */
  research: 'research',
  /** Running synthetic/parametric simulations. */
  simulation: 'simulation',
  /** Running backtests against fetched historical prices. */
  historical: 'historical',
  /** Viewing or editing configuration only. */
  config: 'config',
} as const
export type OperationalMode = (typeof OperationalMode)[keyof typeof OperationalMode]

/** Simple price-overlay signal rules used for historical backtests. */
export type SignalType = 'momentum' | 'mean-reversion' | 'buy-hold'

/** Raw equity/drawdown time series shared by all engine results. */
export interface ResultSeries {
  dates: string[]
  equity: number[]
  returns: number[]
  drawdowns: number[]
}

/** Common metrics computed from a result series. */
export interface ResultMetrics {
  totalReturn: number
  annualizedReturn: number
  volatility: number
  sharpe: number
  maxDrawdown: number
  winRate: number
  trades: number
}

/** Base result produced by any engine. */
export interface EngineResult extends ResultSeries {
  provenance: Provenance
  /** Human-readable description of how this result was produced. */
  assumptions: string[]
  metrics: ResultMetrics
}

/** Result from the synthetic GBM engine. */
export interface SimulationResult extends EngineResult {
  provenance: typeof Provenance.synthetic
  seed: number
  annualReturn: number
  annualVol: number
  years: number
}

/** Result from the historical Yahoo Finance overlay engine. */
export interface HistoricalResult extends EngineResult {
  provenance: typeof Provenance.real
  signalType: SignalType
  signalDescription: string
}

/** A single allocation slice in a portfolio. */
export interface Allocation {
  strategyId: number
  name: string
  category: string
  weight: number
}

/** Result from the portfolio engine. */
export interface PortfolioResult {
  provenance: typeof Provenance.synthetic
  allocations: Allocation[]
  expectedReturn: LabeledValue<number>
  expectedVolatility: LabeledValue<number>
  sharpe: LabeledValue<number>
  assumptions: string[]
}

/** Runtime health/status object. Use this instead of hardcoded UI badges. */
export interface SystemStatus {
  mode: OperationalMode
  strategiesLoaded: number
  sources: {
    name: string
    connected: boolean
    provenance: Provenance
    note: string
  }[]
  cosmeticMetrics: string[]
  hardcodedAssumptions: string[]
  stubbedFeatures: string[]
  lastError: string | null
}

/** Configuration for the synthetic simulation engine. */
export interface SimulationEngineConfig {
  initialCapital: number
  years: number
  annualReturn: number
  annualVol: number
  seed: number
}

/** Configuration for the historical overlay engine. */
export interface HistoricalEngineConfig {
  initialCapital: number
  bars: {
    date: string
    close: number
  }[]
  signalType: SignalType
}

/** Configuration for the portfolio engine. */
export interface PortfolioEngineConfig {
  allocations: Allocation[]
}

/** Helper to label any value. */
export function label<T>(
  value: T,
  provenance: Provenance,
  source: string,
  note?: string
): LabeledValue<T> {
  return { value, provenance, source, note }
}
